# Generated by Django 4.2.5 on 2023-10-06 19:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0003_product_sub_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moving_text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='brands',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/Brand_images'),
        ),
        migrations.AddField(
            model_name='categorie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/Subcategory_images'),
        ),
        migrations.AddField(
            model_name='main_categorie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/Main_category_images'),
        ),
    ]
