# Generated by Django 4.2.5 on 2023-10-07 08:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0004_moving_text_brands_image_categorie_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordered_product',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
