# Generated by Django 4.2.5 on 2023-10-07 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0005_order_ordered_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/Order_item')),
                ('quantity', models.IntegerField()),
                ('price', models.CharField(max_length=150)),
                ('total', models.CharField(max_length=180)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecommerceapp.order')),
            ],
        ),
    ]
