# Generated by Django 4.2.5 on 2023-10-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0006_order_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_product',
            field=models.TextField(null=True),
        ),
    ]
