# Generated by Django 4.2.5 on 2023-10-07 09:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0007_alter_order_ordered_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_product',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
