# Generated by Django 4.2.5 on 2023-10-13 05:54

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Ecommerceapp', '0014_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cart',
        ),
        migrations.AddField(
            model_name='sm_banner',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ecommerceapp.categorie'),
        ),
        migrations.AddField(
            model_name='sm_banner',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ecommerceapp.section'),
        ),
        migrations.AlterField(
            model_name='additional_info',
            name='detail',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='additional_info',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ecommerceapp.product'),
        ),
        migrations.AlterField(
            model_name='additional_info',
            name='specification',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='Brand_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='Description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='Discount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='Image',
            field=models.ImageField(null=True, upload_to='media/Banner_imgs'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='Link',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='Sale',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='brands',
            name='Brand_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='discount_deal',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='main_categorie',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='moving_text',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='moving_text',
            name='text',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='additional_info',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='firstname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='lastname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='zip_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order_item',
            name='image',
            field=models.ImageField(null=True, upload_to='images/Order_item'),
        ),
        migrations.AlterField(
            model_name='order_item',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ecommerceapp.order'),
        ),
        migrations.AlterField(
            model_name='order_item',
            name='price',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='order_item',
            name='product',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order_item',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order_item',
            name='total',
            field=models.CharField(max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='orderupdate',
            name='delivered',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='orderupdate',
            name='order_id',
            field=models.IntegerField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='orderupdate',
            name='timestamp',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderupdate',
            name='update_desc',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='partners',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='partners',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Availability',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ecommerceapp.categorie'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Discount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_info',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Ecommerceapp.section'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='media/Product_images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product_image',
            name='image_url',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='product_image',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ecommerceapp.product'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sliders',
            name='Brand_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sliders',
            name='Description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sliders',
            name='Discount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sliders',
            name='Image',
            field=models.ImageField(null=True, upload_to='media/slider_imgs'),
        ),
        migrations.AlterField(
            model_name='sliders',
            name='Link',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='sliders',
            name='Sale',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sm_banner',
            name='Discount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sm_banner',
            name='Discount_deal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ecommerceapp.discount_deal'),
        ),
        migrations.AlterField(
            model_name='sm_banner',
            name='Image',
            field=models.ImageField(null=True, upload_to='media/sm_banners'),
        ),
        migrations.AlterField(
            model_name='sm_banner',
            name='Key_point_2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sm_banner',
            name='Link',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='sub_categorie',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
