# Generated by Django 4.2.5 on 2023-10-13 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0016_rename_sm_banner_banners'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='Image',
            new_name='image',
        ),
    ]
