# Generated by Django 4.2.5 on 2023-10-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0018_rename_image_banners_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='banners',
            name='Key_point_1',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
