# Generated by Django 4.2.5 on 2023-10-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0019_banners_key_point_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners',
            name='Key_point_1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='banners',
            name='Key_point_2',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
