# Generated by Django 4.2.5 on 2023-10-30 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0024_alter_comment_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='numeric_rating',
        ),
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
