# Generated by Django 4.2.5 on 2023-10-30 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0025_remove_comment_numeric_rating_comment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='numeric_rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0),
        ),
    ]
