# Generated by Django 4.2.5 on 2023-10-31 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0028_comment_created_at_alter_comment_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header_Icons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Icon', models.CharField(max_length=200, null=True)),
                ('Category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ecommerceapp.categorie')),
            ],
        ),
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
