# Generated by Django 4.2.5 on 2023-10-31 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0029_header_icons_delete_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='header_icons',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
