# Generated by Django 4.2.5 on 2023-10-31 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0030_header_icons_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='header_icons',
            name='name',
        ),
    ]
