# Generated by Django 4.2.5 on 2023-11-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0031_remove_header_icons_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='main_categorie',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sub_categorie',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
    ]
