# Generated by Django 3.0.14 on 2023-11-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0035_auto_20231109_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
