# Generated by Django 4.2.7 on 2023-11-12 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0047_remove_product_color_remove_product_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variant_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='Product_images/Variant_images')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecommerceapp.variants')),
            ],
        ),
    ]
