# Generated by Django 4.2.7 on 2023-11-12 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0048_variant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant_image',
            name='product',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ecommerceapp.product'),
        ),
    ]
