# Generated by Django 4.2.7 on 2023-11-12 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0052_remove_variants_imagva'),
    ]

    operations = [
        migrations.AddField(
            model_name='variants',
            name='images',
            field=models.ImageField(null=True, upload_to='Product_images/Variant_images'),
        ),
    ]
