# Generated by Django 4.2.7 on 2023-11-12 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0054_remove_variants_images_variants_image_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='variants',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=500, null=True),
        ),
    ]
