# Generated by Django 4.2.7 on 2023-11-12 20:58

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0055_variants_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variants',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='title', unique=True),
        ),
    ]
