# Generated by Django 4.2.7 on 2023-11-12 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0059_alter_variants_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='variants',
            name='variant_images',
            field=models.ManyToManyField(to='Ecommerceapp.variant_image'),
        ),
    ]
