# Generated by Django 4.2.7 on 2023-11-12 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0060_variants_variant_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variants',
            name='variant_images',
        ),
    ]
