# Generated by Django 4.2.7 on 2023-11-13 00:24

import Ecommerceapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0061_remove_variants_variant_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Ecommerceapp.models.Product.get_upload_path),
        ),
    ]
