# Generated by Django 4.2.7 on 2023-11-13 01:41

import Ecommerceapp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0063_alter_variants_image_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='products',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(related_name='cart_items', to='Ecommerceapp.cartitem'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='brand_name',
            field=models.CharField(default='default_brand_value', max_length=50),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='model_name',
            field=models.CharField(default='Model name', max_length=120),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='packing_cost',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='tag_name',
            field=models.CharField(default='Tag name', max_length=50),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='tax',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ecommerceapp.variants'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variant_color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variant_image',
            field=models.ImageField(blank=True, null=True, upload_to='Cart_images'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variant_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variant_size',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variant_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='Ecommerceapp.cart'),
        ),
        migrations.AlterField(
            model_name='variant_image',
            name='image',
            field=models.ImageField(null=True, upload_to=Ecommerceapp.models.Variant_image.get_upload_path),
        ),
    ]
