# Generated by Django 4.2.7 on 2023-11-13 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0065_remove_cartitem_cart_remove_cartitem_variant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variants',
            name='id',
            field=models.CharField(editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
